kind: Service
apiVersion: v1
metadata:
  name:  frontend-services
  namespace: production
spec:
  selector:
    app:  frontend
  type:   NodePort
  ports:
  - protocol: TCP
    port:  80
    targetPort:  80
    nodePort: 30080