apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend

spec:
  replicas: 1             # base = 1. Overlays change this
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:1.25-alpine
        resources:
         requests:
            memory: "64Mi"
            cpu: "100m"