apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml       # list all base files here
- service.yaml
commonLabels:            # labels added to everything
  app: myapp
  managed-by: kustomize